config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|ru/ do
    devise_for :users

    get '/clean', to: 'bookings#new'
    get '/terms', to: 'home#terms'
    get '/questions', to: 'home#questions'
    root to: "home#home"
    get '/book', to: 'bookings#new'
    get '/bookings', to: 'bookings#new'
    resources :bookings, only: [:new, :create]

    get '/oops', to: 'home#oops'
    get '/status', to: 'home#status'

    get '/about', to: 'home#about'

    root to: "home#home"
  end


  # devise_for :admins


  # get '/clean', to: 'bookings#new'

  resources :notifications, only: :create
  # resources :promos, only: :index
  # resources :notifications, constraints: { host: ENV['PAYTURE_HOST'] }, only: :create
  # post '/notifications', to: 'notications#create', constraints: { protocol: 'https://', host: ENV['PAYTURE_HOST'] }


  # get '/admin/dashboard', to: 'admin#index'

  # post '/subscribe', to: 'subscribe#subscribe'

  # get '/terms', to: 'home#terms'
  # get '/questions', to: 'home#questions'

  # root to: "home#home"
  # get '/beta', to: "home#home"

  # get '/book', to: 'bookings#new'
  # get '/bookings', to: 'bookings#new'
  # resources :bookings, only: [:new, :create]
  #
  # get '/oops', to: 'home#oops'
  # get '/status', to: 'home#status'

  post '/callback', to: 'home#callback'
  post '/newsletter', to: 'home#newsletter'

  namespace :admin do
    # get '/notifications', to: 'admin#notifications'
    resources :bookings do
      member do
        get :activate
        get :cancel
      end
    end
    resources :promos
    resources :professionals
    resources :users do
      member do
        get :add_card
        delete :remove_card
      end
    end
    resources :invoices do
      member do
        put :charge
      end
    end
    resources :occurrences
  end

  get '/admin', to: 'admin/bookings#index'

  post '/notification', to: 'notifications#create'

end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :booking

  # scope :charged_this_week, -> { charged.where("date >= ?", Date.today.beginning_of_week) }
  scope :charged_between, -> (a, b) { charged.where(date: a..b) }

  enum status: [:draft, :pending, :failed, :charged]

  before_create :create_token

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
      :with_date_equal  ,
      :with_status_ids  ,
      :search_query     ,
      :sorted_by
    ]
  )

  # scope :sorted_by, lambda { |sort_key| }
  scope :with_status_ids, lambda { |status_ids| where(status: [*status_ids]) }
  scope :with_date_equal, lambda { |ref_date| where(date: ref_date) }
  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? :desc : :asc
    case sort_option.to_s
    when /^created_at_/
      order(created_at: direction)
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }
  scope :search_query, lambda { |query|
    return nil  if query.blank?
    terms = query.downcase.split(/\s+/)
    terms.map! { |e| (e.gsub('*', '%') + '%').gsub(/%+/, '%') }
    num_or_conds = 3

    joins(booking: :user).where(
      terms.map { |term|
        # "(LOWER(users.firstname) LIKE ? OR LOWER(bookings.users.lastname) LIKE ? OR LOWER(users.email) LIKE ?)"
        "(LOWER(users.firstname) LIKE ? OR LOWER(users.lastname) LIKE ? OR LOWER(users.email) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  def self.options_for_sorted_by
    [
      ['Creation date (newest first)', 'created_at_desc'],
      ['Creation date (oldest first)', 'created_at_asc'],
    ]
  end

  # def options_for_sorted_by
  #   ''
  # end

  private

  def create_token
    self.token = SecureRandom.uuid
  end

  # def update_date_format
  #   self.date_format = Date.strptime(self.date, "%d/%m/%Y")
  # end
end

app/controllers/admin/invoices_controller.rb
class Admin::InvoicesController < Admin::AdminController

  before_action :set_invoice, only: [:show, :edit, :update, :destroy, :charge]
  before_action :set_booking, only: [:new]

  def charge
    respond_to do |format|
      if PaytureWalletService.charge(@invoice)
        format.html { redirect_to admin_invoices_path, notice: 'Invoice was charged.' }
      else
        format.html { redirect_to admin_invoices_path, notice: 'Invoice was not charged.' }
      end
    end
  end

  def index
    @filterrific = initialize_filterrific(
      Invoice,
      params[:filterrific],
      select_options: {
        sorted_by: Invoice.options_for_sorted_by,
        with_status_ids: Invoice::statuses
      }
    ) or return
    @invoices = @filterrific.find.page params[:page]

    @charges_daily    = []
    @charges_weekly   = []
    @charges_monthly  = []
    @charges_yearly   = []

    7.times do |i|
      day    = Date.today - i.days
      sWeek   = Date.today.beginning_of_week  - i.week
      eWeek   = Date.today.end_of_week        - i.week
      sMonth  = Date.today.beginning_of_month - i.month
      eMonth  = Date.today.end_of_month       - i.month
      sYear   = Date.today.beginning_of_year  - i.year
      eYear   = Date.today.end_of_year        - i.year
      @charges_daily    << Invoice.charged.where(date: day).sum(:amount).to_f
      @charges_weekly   << Invoice.charged_between(sWeek  , eWeek).sum(:amount).to_f
      @charges_monthly  << Invoice.charged_between(sMonth , eMonth).sum(:amount).to_f
      @charges_yearly   << Invoice.charged_between(sYear  , eYear).sum(:amount).to_f
    end
  end

  def edit
    redirect_to admin_invoices_path if @invoice.status == :charged
    @readonly = false
  end

  def new
    @readonly = false
  end

  def show
    @readonly = true
  end

  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to admin_invoices_path, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to admin_invoices_path, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to admin_invoices_path, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:booking_id, :date, :amount)
    end

    def set_booking
      @invoice = Invoice.new
      if params[:booking_id]
        booking = Booking.find(params[:booking_id])
        @invoice.booking = booking
        @invoice.amount = booking.final_total
      end
    end
end

app/helpers/admin/invoices_helper.rb
module Admin::InvoicesHelper

  def invoice_status_label(status)
    content_tag :span, status, class: "label label-#{invoice_color(status)}"
  end

  def percentage_change(v1, v2)
    if v2 > v1
      # Increase
      (v2 - v1) / v1 * 100
    else
      # Decrease
      (v1 - v2) / v1 * 100
    end
  end

  private

  def invoice_color(status)
    color = 'default'
    case status.to_sym
    when :draft
      color = 'warning'
    when :pending, :processing
      color = 'complete'
    when :charged
      color = 'success'
    else
      color = 'danger'
    end
    color
  end

end

app/views/admin/invoices/_form.html.erb
<%= form_for [:admin, @invoice], html: { class: "form-horizontal" } do |f| %>

  <div class="form-group">
    <%= f.label :booking, class: "col-sm-4 control-label" %>
    <div class="col-sm-8">
      <!--email_off-->
      <%= f.select(:booking_id, Booking.all.collect { |b| ["#{b.user.email} - #{b.order_token}", b.id] }, {}, { class: 'form-control', readonly: @readonly }) %>
      <!--/email_off-->
    </div>
  </div>

  <div class="form-group">
    <%= f.label :date, class: 'col-sm-4 control-label' %>
    <div class="col-sm-4">
      <div class="input-group date" id="datepicker">
        <%= f.text_field :date, class: "form-control", required: true, readonly: @readonly %>
        <span class="input-group-addon"><i class="fa fa-calendar"></i>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :amount, class: 'col-sm-4 control-label' %>
    <div class="col-sm-4">
      <%= f.text_field :amount, class: "form-control", required: true, readonly: @readonly %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-4">
      <%= f.label :token, class: 'control-label' %>
      <p class="text-danger small">Warning: Leave this field empty</p>
    </div>
    <div class="col-sm-4">
      <%= f.text_field :token, class: "form-control", readonly: true %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-8 offset-sm-4">
      <% if @readonly %>
        <%= link_to 'Edit', edit_admin_invoice_path(@invoice), class: 'btn btn-default' unless @invoice.status == :charged %>
      <% else %>
        <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

<% end %>

<% content_for :foot do %>
  <script type="text/javascript">

    $('#datepicker').datepicker({
      format: 'dd/mm/yyyy'
    });

  </script>
<% end %>

app/views/admin/invoices/_list.html.erb
<table class="table table-condensed">
  <thead>
    <th>Status</th>
    <th>Date</th>
    <th>Amount</th>
    <th>Name</th>
    <!-- <th>Email</th> -->
    <th>Error</th>
    <th></th>
  </thead>
  <tbody>
    <% invoices.each do |invoice| %>
    <tr>
      <td class="v-align-middle"><%= invoice_status_label(invoice.status) %></td>
      <td class="v-align-middle"><%= invoice.date.strftime('%d/%m/%Y') %></td>
      <td class="v-align-middle"><%= number_to_currency(invoice.amount, unit: '₽') %></td>
      <td class="v-align-middle"><%= link_to invoice.booking.user.try(:sort_name), [:admin, invoice.booking.user] %></td>
      <!-- <td class="v-align-middle"><%= link_to invoice.booking.user.try(:email), [:admin, invoice.booking.user] %></td> -->
      <td class="v-align-middle"><%= invoice.error %></td>
      <td class="v-align-middle">
        <div class="btn-group btn-group btn-group-justified pull-right">
          <%= link_to [:admin, invoice], class: 'btn btn-complete btn-sm' do %>
            <i class="fa fa-info"></i>
          <% end %>
          <%= link_to charge_admin_invoice_path(invoice), method: :put, class: "btn btn-primary btn-sm #{!invoice.draft? ? 'disabled' : ''}" do %>
            <i class="fa fa-credit-card-alt"></i>
          <% end %>
          <%= link_to admin_invoice_path(invoice), method: :delete, class: "btn btn-danger btn-sm #{!invoice.draft? ? 'disabled' : ''}" do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<div class="text-center">
  <%= paginate invoices %>
</div>

app/views/admin/invoices/_sales_widget_bar.html.erb
<div class="widget-9 panel no-border bg-primary no-margin widget-loader-bar">
  <div class="container-xs-height full-height">
    <div class="row-xs-height">
      <div class="col-xs-height col-top">
        <div class="panel-heading  top-left top-right">
          <div class="panel-title text-black">
            <span class="font-montserrat fs-11 all-caps">Weekly Sales
              <i class="fa fa-chevron-right"></i>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="row-xs-height">
      <div class="col-xs-height col-top">
        <div class="p-l-20 p-t-15">
          <h3 class="no-margin p-b-5 text-white"><%= number_to_currency(@total_charged_this_week, unit: "₽") %></h3>
          <% if @total_charged_1_week_ago > @total_charged_this_week %>
            <i class="fa fa-arrow-circle-down text-white"></i>
          <% else %>
            <i class="fa fa-arrow-circle-up text-white"></i>
          <% end %>
          <span class="small hint-text">
            <%= percentage_change(@total_charged_1_week_ago, @total_charged_this_week, "last week") %>
          </span>
        </div>
      </div>
    </div>
    <div class="row-xs-height">
      <div class="col-xs-height col-bottom">
        <div class="progress progress-small m-b-20">

          <div class="progress-bar progress-bar-white" style="width:<%= number_to_percentage(@total_charged_this_week/@total_charged_1_week_ago*100) %>"></div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/invoices/_sales_widget_chart.html.erb
<div class="widget-8 panel no-border bg-<%= background %> no-margin widget-loader-bar">
  <div class="container-xs-height full-height">
    <div class="row-xs-height">
      <div class="col-xs-height col-top">
        <div class="panel-heading top-left top-right">
          <div class="panel-title text-white hint-text">
            <span class="font-montserrat fs-11 all-caps"><%= name %>
              <i class="fa fa-chevron-right"></i>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="row-xs-height ">
      <div class="col-xs-height col-top relative">
        <div class="row">
          <div class="col-sm-6">
            <div class="p-l-20">
              <h3 class="no-margin p-b-5 text-white"><%= number_to_currency(data[0], unit: '₽'[0]) %></h3>
              <p class="small text-white m-t-5">

                <span class="label font-montserrat m-r-5">
                  <%= number_to_percentage(percentage_change(data[0], data[1]), precision: 0) %>
                </span>
                <%= data[0] > data[1] ? "Higher" : "Lower"  %>
              </p>
            </div>
          </div>
          <div class="col-sm-6"></div>
        </div>
        <div class='widget-8-chart widget-<%= name.downcase.parameterize %> line-chart' data-line-color="black" data-points="true" data-point-color="success" data-stroke-width="2">
          <svg></svg>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :foot do %>

<script type="text/javascript">

  var <%= name.downcase.parameterize('_') %>_data = [{
    key: "<%= name %>",
    values: [
      [100, <%= data[6] %>],
      [150, <%= data[5] %>],
      [200, <%= data[4] %>],
      [250, <%= data[3] %>],
      [300, <%= data[2] %>],
      [350, <%= data[1] %>],
      [400, <%= data[0] %>]
    ]
  }]

  nv.addGraph((function() {
    var chart;
    chart = nv.models.lineChart().x(function(d) {
      return d[0];
    }).y(function(d) {
      return d[1];
    }).color(['#000']).margin({
      top: 10,
      right: -10,
      bottom: -10,
      left: -10
    }).showXAxis(false).showYAxis(false).showLegend(false).interactive(false).forceY([0,<%= data.max %> * 1.1]);
    d3.select('.widget-<%= name.downcase.parameterize %> svg').datum(<%= name.downcase.parameterize('_') %>_data).call(chart);
    nv.utils.windowResize(chart.update);
    nv.utils.windowResize(function() {
      setTimeout((function() {
        $('.widget-<%= name.downcase.parameterize %> .nvd3 circle.nv-point').attr('r', '3').css({
          'stroke-width': '2px',
          ' stroke-opacity': 0.4
        });
      }), 500);
    });
    return chart;
  }), function() {
    setTimeout((function() {
      $('.widget-<%= name.downcase.parameterize %> .nvd3 circle.nv-point').attr('r', '3').css({
        'stroke-width': '2px',
        ' stroke-opacity': 0.4
      });
    }), 500);
  });
</script>

<% end %>

app/views/admin/invoices/edit.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= render "form" %>
  </div>
</div>

app/views/admin/invoices/index.html.erb
<div class="row p-b-20">
  <div class="col-sm-3">
    <%= render partial: 'sales_widget_chart', locals: { data: @charges_daily  , name: 'Daily sales'   , background: 'complete' } %>
  </div>
  <div class="col-sm-3">
    <%= render partial: 'sales_widget_chart', locals: { data: @charges_weekly , name: 'Weekly sales'  , background: 'success' } %>
  </div>
  <div class="col-sm-3">
    <%= render partial: 'sales_widget_chart', locals: { data: @charges_monthly, name: 'Monthly sales' , background: 'complete' } %>
  </div>
  <div class="col-sm-3">
    <%= render partial: 'sales_widget_chart', locals: { data: @charges_yearly , name: 'Yearly sales'  , background: 'success' } %>
  </div>
</div>

<div class="panel panel-default">

  <div class="panel-heading">
    <%= form_for_filterrific @filterrific do |f| %>
    <div class="row">
      <div class="col-sm-2">
        <%= f.text_field :search_query, class: 'filterrific-periodically-observed form-control', placeholder: 'Search' %>
      </div>
      <div class="col-sm-2">
        <div id="datepicker" class="input-group date">
          <%= f.text_field :with_date_equal, class: "form-control", disabled: @readonly, placeholder: 'Date' %>
          <span class="input-group-addon">
            <i class="fa fa-calendar"></i>
          </span>
        </div>
      </div>
      <div class="col-sm-2">
        <%= f.select :with_status_ids, Invoice.statuses.collect { |s| ["#{s[0]} (#{Invoice.send(s[0]).count})", s[1]] }, { include_blank: "All (#{Invoice.count})" }, { class: 'form-control' } %>
      </div>
      <div class="col-sm-2">
        <%= f.select :sorted_by, @filterrific.select_options[:sorted_by], { include_blank: false }, class: 'form-control' %>
      </div>
      <div class="col-sm-2">
        <%= link_to 'Reset filters', reset_filterrific_url, class: 'btn btn-default' %>
      </div>
    </div>
    <%# render_filterrific_spinner %>
    <% end %>
  </div>

  <!-- <div class="row">
      <div class="col-sm-6">
        <%= link_to 'Create Invoice', new_admin_invoice_path, class: 'btn btn-default' %>
      </div>
      <div class="col-sm-6">
        <div class="pull-right">

        </div>
      </div>
    </div>
  </div> -->

  <div class="panel-body">
    <div id="filterrific_results">
      <%= render partial: 'list', locals: { invoices: @invoices } %>
    </div>
  </div>
</div>

<% content_for :foot do %>
<script type="text/javascript">
  $(document).ready(function () {
    $('#datepicker').datepicker({format: 'dd/mm/yyyy'});
  });
</script>
<% end %>

app/views/admin/invoices/index.js.erb
<% js = escape_javascript(
  render(partial: 'list', locals: { invoices: @invoices })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/admin/invoices/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">
      Create a new invoice
    </h1>
  </div>
  <div class="panel-body">
    <%= render "form" %>
  </div>
</div>

app/views/admin/invoices/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <%= render "form" %>
  </div>
</div>