config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|ru/ do
    devise_for :users

    get '/clean', to: 'bookings#new'
    get '/terms', to: 'home#terms'
    get '/questions', to: 'home#questions'
    root to: "home#home"
    get '/book', to: 'bookings#new'
    get '/bookings', to: 'bookings#new'
    resources :bookings, only: [:new, :create]

    get '/oops', to: 'home#oops'
    get '/status', to: 'home#status'

    get '/about', to: 'home#about'

    root to: "home#home"
  end


  # devise_for :admins


  # get '/clean', to: 'bookings#new'

  resources :notifications, only: :create
  # resources :promos, only: :index
  # resources :notifications, constraints: { host: ENV['PAYTURE_HOST'] }, only: :create
  # post '/notifications', to: 'notications#create', constraints: { protocol: 'https://', host: ENV['PAYTURE_HOST'] }


  # get '/admin/dashboard', to: 'admin#index'

  # post '/subscribe', to: 'subscribe#subscribe'

  # get '/terms', to: 'home#terms'
  # get '/questions', to: 'home#questions'

  # root to: "home#home"
  # get '/beta', to: "home#home"

  # get '/book', to: 'bookings#new'
  # get '/bookings', to: 'bookings#new'
  # resources :bookings, only: [:new, :create]
  #
  # get '/oops', to: 'home#oops'
  # get '/status', to: 'home#status'

  post '/callback', to: 'home#callback'
  post '/newsletter', to: 'home#newsletter'

  namespace :admin do
    # get '/notifications', to: 'admin#notifications'
    resources :bookings do
      member do
        get :activate
        get :cancel
      end
    end
    resources :promos
    resources :professionals
    resources :users do
      member do
        get :add_card
        delete :remove_card
      end
    end
    resources :invoices do
      member do
        put :charge
      end
    end
    resources :occurrences
  end

  get '/admin', to: 'admin/bookings#index'

  post '/notification', to: 'notifications#create'

end

app/models/promo.rb
class Promo < ApplicationRecord

  validates :code, uniqueness: true

  has_many :bookings
end

app/controllers/admin/promos_controller.rb
class Admin::PromosController < Admin::AdminController
  before_action :set_promo, only: [:show, :edit, :update, :destroy]

  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
  end

  # GET /promos/new
  def new
    @promo = Promo.new
  end

  # GET /promos/1/edit
  def edit
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(promo_params)

    respond_to do |format|
      if @promo.save
        format.html { redirect_to admin_promos_path, notice: 'Promo was successfully created.' }
        format.json { render :show, status: :created, location: @promo }
      else
        format.html { render :new }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /promos/1
  # PATCH/PUT /promos/1.json
  def update
    respond_to do |format|
      if @promo.update(promo_params)
        format.html { redirect_to admin_promos_path, notice: 'Promo was successfully updated.' }
        format.json { render :show, status: :ok, location: @promo }
      else
        format.html { render :edit }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo.destroy
    respond_to do |format|
      format.html { redirect_to admin_promos_path, notice: 'Promo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_promo
      @promo = Promo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def promo_params
      params.require(:promo).permit(:code, :discount)
    end
end

app/views/admin/promos/_form.html.erb
<%= form_for [:admin, @promo] do |f| %>
  <div class="form-group form-group-default col-sm-6">
    <%= f.label :code %>
    <%= f.text_field :code, class: 'form-control' %>
  </div>
  <div class="form-group form-group-default col-sm-6">
    <%= f.label :discount %>
    <%= f.number_field :discount, class: 'form-control' %>
  </div>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/admin/promos/edit.html.erb
<%= render partial: "form" %>

app/views/admin/promos/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title col-xs-12">
      Promos
      <span class="pull-right">
        <%= link_to "Add New", new_admin_promo_path, class: 'btn btn-primary' %>
      </span>
    </div>
  </div>
  <div class="panel-body">
    <div class="table-responsive col-xs-12">
      <table class="table table-hover table-condensed">
        <thead>
          <tr>
            <th>Code</th>
            <th>Discount</th>
            <th>Created At</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @promos.each do |p| %>
          <tr>
            <td><%= p.code %></td>
            <td><%= p.discount %></td>
            <td><%= p.created_at %></td>
            <td><%= link_to "Delete", admin_promo_path(p), method: :delete, class: "btn btn-danger" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/promos/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">New Promo</div>
  </div>
  <div class="panel-body">
    <%= render partial: "form" %>
  </div>
</div>