config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|ru/ do
    devise_for :users

    get '/clean', to: 'bookings#new'
    get '/terms', to: 'home#terms'
    get '/questions', to: 'home#questions'
    root to: "home#home"
    get '/book', to: 'bookings#new'
    get '/bookings', to: 'bookings#new'
    resources :bookings, only: [:new, :create]

    get '/oops', to: 'home#oops'
    get '/status', to: 'home#status'

    get '/about', to: 'home#about'

    root to: "home#home"
  end


  # devise_for :admins


  # get '/clean', to: 'bookings#new'

  resources :notifications, only: :create
  # resources :promos, only: :index
  # resources :notifications, constraints: { host: ENV['PAYTURE_HOST'] }, only: :create
  # post '/notifications', to: 'notications#create', constraints: { protocol: 'https://', host: ENV['PAYTURE_HOST'] }


  # get '/admin/dashboard', to: 'admin#index'

  # post '/subscribe', to: 'subscribe#subscribe'

  # get '/terms', to: 'home#terms'
  # get '/questions', to: 'home#questions'

  # root to: "home#home"
  # get '/beta', to: "home#home"

  # get '/book', to: 'bookings#new'
  # get '/bookings', to: 'bookings#new'
  # resources :bookings, only: [:new, :create]
  #
  # get '/oops', to: 'home#oops'
  # get '/status', to: 'home#status'

  post '/callback', to: 'home#callback'
  post '/newsletter', to: 'home#newsletter'

  namespace :admin do
    # get '/notifications', to: 'admin#notifications'
    resources :bookings do
      member do
        get :activate
        get :cancel
      end
    end
    resources :promos
    resources :professionals
    resources :users do
      member do
        get :add_card
        delete :remove_card
      end
    end
    resources :invoices do
      member do
        put :charge
      end
    end
    resources :occurrences
  end

  get '/admin', to: 'admin/bookings#index'

  post '/notification', to: 'notifications#create'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # layout :layout

  def index
    # Do nothing
  end

  def home
    render layout: 'frontend'
  end

  def about
    render layout: 'frontend'
  end

  def terms
    render layout: 'frontend'
    # if I18n.locale == :ru
    #   # redirect_to 'https://support.getshiny.ru/hc/ru/articles/115000783729'
    # else
    #   # redirect_to 'https://support.getshiny.ru/hc/en-us/articles/115000783729'
    # end
  end

  def questions
    render layout: 'frontend'
    # if I18n.locale == :ru
    #   # redirect_to 'https://support.getshiny.ru/hc/ru/sections/115000222769'
    # else
    #   # redirect_to 'https://support.getshiny.ru/hc/en-us/sections/115000222769'
    #   redirect_to 'https://getshiny.zendesk.com/hc/en-us/categories/115000106365-FAQ'
    # end
  end

  def callback
    Slacked.post "Callback: #{params[:phone]}"
    head :ok
  end

  def newsletter
    Slacked.post "Newsletter: #{params[:email]}"
    head :ok
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.erb
<!-- <section class="p-b-60 p-t-60 b-b b-grey"> -->
<%= content_tag :section, class: 'm-t-50 p-b-60 p-t-60' do %>
    <div class="container">
      <h3><%= t('about.title') %></h3>
      <p><%= t('about.p1') %></p>
      <p><%= t('about.p2') %></p>

      <div class="row m-t-40 text-center">
        <div class="col-xs-6">
          <%= image_tag 'profiles/6.jpg', width: 100, height: 100, src: image_path('profiles/6x.jpg'), class: 'img-circle m-b-20', data: { src_retina: image_path('profiles/6x.jpg'), src: image_path('profiles/6.jpg') } %>
          <div>
            <%= inline_svg 'flags/ch.svg', height: 15, width: 20 %>
          </div>
          <h4 class="lead m-b-5"><%= t('home.team.team.t1.title') %></h4>
          <small><%= t('from') %></small><br>
          <small><%= t('home.team.team.t1.subtitle') %></small>
        </div>
        <div class="col-xs-6">
            <%= image_tag 'profiles/7.jpg', width: 100, height: 100, src: image_path('profiles/7x.jpg'), class: 'img-circle m-b-20', data: { src_retina: image_path('profiles/7x.jpg'), src: image_path('profiles/7.jpg') } %>
            <div>
              <%= inline_svg 'flags/fr.svg', height: 15, width: 20 %>
            </div>
            <h4 class="lead m-b-5"><%= t('home.team.team.t2.title') %></h4>
            <small><%= t('from') %></small><br>
            <small><%= t('home.team.team.t2.subtitle') %></small>
        </div>
    </div>
    </div>
<!-- </section> -->
<% end %>

app/views/home/home.html.erb
<%= render 'home/sections/hero' %>
<%= render 'home/sections/about' %>
<%= render 'home/sections/benefits' %>
<%= render 'home/sections/team' %>
<%= render 'home/sections/customers' %>
<%= render 'home/sections/partners' %>
<%= render 'home/sections/book' %>
<%= render 'home/sections/newsletter' %>
<%= render 'home/sections/callback' %>
<%= render 'home/sections/checklist' %>

app/views/home/index.html.erb
<section class="jumbotron height-70 full-width hero_1" data-pages="parallax">
    <div class="inner full-height">
        <div class="container-xs-height full-height">
            <div class="col-xs-height col-middle text-left">
                <div class="container">
                    <div class="col-sm-8 col-sm-offset-2 sm-m-t-30 sm-p-t-20 sm-p-b-20">
                        <h2 class="dark text-center text-black xs-p-t-30 sm-p-b-30">
                            <%= raw t('home.section1.text1') %>
                        </h2>
                        <div class="text-center m-t-30 col-md-8 col-md-offset-2">
                            <!-- <%= link_to t('menu.order'), clean_path, { class: 'btn btn-lg btn-primary btn-cons btn-block text-white', data: { turbolinks: false } }%> -->
                            <button class="btn btn-lg btn-primary btn-cons btn-block text-white" data-toggle="modal" data-target="#orderModal"><%= t('menu.order') %></button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section>
    <div class="row p-t-50 p-b-50">
        <div class="col-sm-3 text-center">
            <i class="fa fa-4x fa-clock-o"></i>
            <h4 class="m-t-10"><%= t('home.section2.text1') %></h4>
        </div>
        <div class="col-sm-3 text-center">
            <i class="fa fa-4x fa-shield"></i>
            <h4 class="m-t-10"><%= t('home.section2.text2') %></h4>
        </div>
        <div class="col-sm-3 text-center">
            <i class="fa fa-4x fa-credit-card"></i>
            <h4 class="m-t-10"><%= t('home.section2.text3') %></h4>
        </div>
        <div class="col-sm-3 text-center">
            <i class="fa fa-4x fa-language"></i>
            <h4 class="m-t-10"><%= t('home.section2.text4') %></h4>
        </div>
    </div>
</section>

<section class="p-b-100 p-t-100 bg-master-dark">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <h6 class="block-title m-b-0 text-white text-center"><%= t('home.section3.text1') %></h6>
                <h1 class="text-white text-center m-t-5"><%= t('home.section3.text2') %></h1>
                <!-- <p class="small hint-text p-t-0 text-white text-center ">We value your privacy. None of the details supplied will be shared with external parties</p> -->
                <div class="form-group form-group-default input-group  m-t-40 bg-transparent b-a b-transparent-white">
                    <label>Email</label>
                    <input type="email" id="subscribeEmail" class="form-control text-white" placeholder="example@mailserver.com">
                    <span class="input-group-btn">
                        <button id="subscribeButton" class="btn btn-primary m-r-10 btn-cons" type="button"><%= t('home.section3.text3') %></button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="p-b-20 p-t-20 bg-master-light">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2 text-center">
                <h4 class="block-title m-b-0 text-master text-center"><%= t('home.partners') %></h4>
                <br>
                <div class="col-sm-6">
                <%= image_tag "iwc.png", height: 100 %>
              </div>
                <div class="col-sm-6">
                <%= image_tag "rosinka.png", height: 100 %>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="p-b-100 p-t-100">
    <h3 class="text-center"><%= t('home.section4.text1') %></h3>
    <div class="row m-t-50">
        <div class="col-sm-4 text-center">
            <h1>1</h2>
            <h4 class="m-t-10"><%= t('home.section4.text2') %></h4>
        </div>
        <div class="col-sm-4 text-center">
            <h1>2</h2>
            <h4 class="m-t-10"><%= t('home.section4.text3') %></h4>
        </div>
        <div class="col-sm-4 text-center">
            <h1>3</h2>
            <h4 class="m-t-10"><%= t('home.section4.text4') %></h4>
        </div>
    </div>
    <div class="row m-t-50">
        <div class="col-sm-6 col-sm-offset-3 text-center">
            <!-- <%= link_to t('home.section4.text5'), clean_path, { class: 'btn btn-lg btn-primary btn-cons btn-block text-white', data: { turbolinks: false } }%> -->
            <button class="btn btn-lg btn-primary btn-cons btn-block text-white" data-toggle="modal" data-target="#orderModal"><%= t('home.section4.text5') %></button>
        </div>
    </div>
</section>

app/views/home/oops.html.erb
<div style="height: 80vh">
<div class="container m-t-90">

  <div class="panel panel-default">
      <div class="panel-heading">
          Payment provider is down
      </div>
      <div class="panel-body">
        Our payment provider is currently unreachable. But rest assured, <b>your booking has been registered</b>. We will contact you asap.
      </div>
  </div>
</div>
</div>

app/views/home/questions.html.erb
<%= content_tag :section, class: 'm-t-50 p-b-60 p-t-60' do %>
  <div class="container">
    <h3 class="m-b-40"><%= t('questions.title') %></h1>

    <div class="panel-group" data-toggle="collapse" id="accordion">
        <!-- BEGIN - Question 1 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapse1"><%= t('questions.q1.title') %></a>
                </h4>
            </div>
            <div class="panel-collapse collapse" id="collapse1">
                <div class="panel-body">
                    <p><%= t('questions.q1.p1') %></p>
                    <p><%= t('questions.q1.p2') %></p>
                    <ol>
                      <li><%= t('questions.q1.b1') %> <%= link_to t('order'), clean_path %></li>
                      <!-- <li><%= t('questions.q1.b2') %></li> -->
                      <li><%= t('questions.q1.b3') %></li>
                      <li><%= t('questions.q1.b4') %></li>
                      <li><%= t('questions.q1.b5') %></li>
                    </ol>
                </div>
            </div>
        </div>
        <!-- END - Question 1 -->

        <!-- BEGIN - Question 2 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapse2"><%= t('questions.q2.title') %></a>
                </h4>
            </div>
            <div class="panel-collapse collapse" id="collapse2">
                <div class="panel-body">
                    <p><%= t('questions.q2.p1') %></p>
                    <p><%= t('questions.q2.p2') %> <%= link_to t('order'), clean_path %></p>
                </div>
            </div>
        </div>
        <!-- END - Question 2 -->

        <!-- BEGIN - Question 3 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapse3"><%= t('questions.q3.title') %></a>
                </h4>
            </div>
            <div class="panel-collapse collapse" id="collapse3">
                <div class="panel-body">
                    <p><%= t('questions.q3.p1') %></p>
                    <p><%= t('questions.q3.p2') %></p>
                    <p><%= t('questions.q3.p3') %></p>
                    <p><%= t('questions.q3.p4') %></p>
                    <table class="table">
                      <thead>
                        <tr>
                          <th class="text-center"><%= t('questions.q3.table.c1r1') %></th>
                          <th class="text-center"><%= t('questions.q3.table.c2r1') %></th>
                          <th class="text-center"><%= t('questions.q3.table.c3r1') %></th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr class="text-center">
                          <td><%= t('questions.q3.table.c1r2') %></td>
                          <td><%= t('questions.q3.table.c2r2') %></td>
                          <td><%= t('questions.q3.table.c3r2') %></td>
                        </tr>
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END - Question 3 -->

        <!-- BEGIN - Question 4 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapse4"><%= t('questions.q4.title') %></a>
                </h4>
            </div>
            <div class="panel-collapse collapse" id="collapse4">
                <div class="panel-body">
                    <p><%= t('questions.q4.p1') %></p>
                    <!-- <p><%= t('questions.q4.p2') %></p> -->
                </div>
            </div>
        </div>
        <!-- END - Question 4 -->

        <!-- BEGIN - Question 5 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapse5"><%= t('questions.q5.title') %></a>
                </h4>
            </div>
            <div class="panel-collapse collapse" id="collapse5">
                <div class="panel-body">
                    <p><%= t('questions.q5.p1') %></p>
                    <p><i class="pg pg-mail"></i> <%= mail_to ENV['SUPPORT_EMAIL'] %></p>
                    <p><i class="pg pg-phone"></i> <%= link_to ENV['PHONE_NUMBER'], "tel:#{ENV['PHONE_NUMBER']}" %></p>
                </div>
            </div>
        </div>
        <!-- END - Question 5 -->

        <!-- BEGIN - Question 6 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapse6"><%= t('questions.q6.title') %></a>
                </h4>
            </div>
            <div class="panel-collapse collapse" id="collapse6">
                <div class="panel-body">
                    <p><%= t('questions.q6.p1') %></p>
                    <ul>
                      <li><%= t('questions.q6.b1') %></li>
                      <li><%= t('questions.q6.b2') %></li>
                      <li><%= t('questions.q6.b3') %></li>
                      <li><%= t('questions.q6.b4') %></li>
                      <li><%= t('questions.q6.b5') %></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- END - Question 6 -->

        <!-- BEGIN - Question 7 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapse7"><%= t('questions.q7.title') %></a>
                </h4>
            </div>
            <div class="panel-collapse collapse" id="collapse7">
                <div class="panel-body">
                    <p><%= t('questions.q7.p1') %></p>
                </div>
            </div>
        </div>
        <!-- END - Question 7 -->

        <!-- BEGIN - Question 8 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapse8"><%= t('questions.q8.title') %></a>
                </h4>
            </div>
            <div class="panel-collapse collapse" id="collapse8">
                <div class="panel-body">
                    <p><%= t('questions.q8.p1') %></p>
                    <p><i class="pg pg-mail"></i> <%= mail_to ENV['SUPPORT_EMAIL'] %></p>
                    <p><i class="pg pg-phone"></i> <%= link_to ENV['PHONE_NUMBER'], "tel:#{ENV['PHONE_NUMBER']}" %></p>
                </div>
            </div>
        </div>
        <!-- END - Question 8 -->

        <!-- BEGIN - Question 9 -->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="collapsed" data-parent="#accordion" data-toggle="collapse" href="#collapse9"><%= t('questions.q9.title') %></a>
                </h4>
            </div>
            <div class="panel-collapse collapse" id="collapse9">
                <div class="panel-body">
                    <p><%= t('questions.q9.p1') %></p>
                    <p><i class="pg pg-mail"></i> <%= mail_to ENV['SUPPORT_EMAIL'] %></p>
                    <p><i class="pg pg-phone"></i> <%= link_to ENV['PHONE_NUMBER'], "tel:#{ENV['PHONE_NUMBER']}" %></p>
                </div>
            </div>
        </div>
        <!-- END - Question 9 -->
    </div>
</div>

<% end %>

app/views/home/status.html.erb
<div style="height: 80vh">
<div class="container m-t-90">

  <div class="panel panel-default">
      <div class="panel-heading">
          Booking successful!
      </div>
      <div class="panel-body">
        Congratulations! We will be in touch asap!
      </div>
  </div>
</div>
</div>

app/views/home/terms.html.erb
<%= content_tag :section, class: 'm-t-50 p-b-60 p-t-60' do %>
  <div class="container">
    <h3><%= t('menu.terms') %></h3>
    <%= render partial: "shared/terms/#{I18n.locale}" %>
  </div>
<% end %>